sanbric_main_homepage:
    path:     /
    defaults: { _controller: SanbricMainBundle:Default:index }

sanbric_saludo:
    path:     /Saluda
    defaults: { _controller: SanbricMainBundle:Default:Saluda }

sanbric_info_inicial:
    path:     /InfoInicial
    defaults: { _controller: SanbricMainBundle:Default:InfoInicial }

sanbric_set_info_inicial:
    path:     /SetInfoInicial
    defaults: { _controller: SanbricMainBundle:Default:SetInfoInicial }

_agregar_datos_empresa:
    path:     /AgregarDatosEmpresa
    defaults: { _controller: SanbricMainBundle:Empresa:AgregarDatosEmpresa }

_obtener_datos_empresa:
    path:     /ObtenerDatosEmpresa
    defaults: { _controller: SanbricMainBundle:Empresa:ObtenerDatosEmpresa }

_actualizar_datos_empresa:
    path:     /ActualizarDatosEmpresa
    defaults: { _controller: SanbricMainBundle:Empresa:ActualizarDatosEmpresa }
